> Entering new AgentExecutor chain...
Traceback (most recent call last):
  File "/exacto/abhishek/responsible_ai/src/main.py", line 26, in <module>
    response = call_csv_agent(question,FILE_PATH)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exacto/abhishek/responsible_ai/src/llm/llm_handler.py", line 44, in call_csv_agent
    response = csv_agent.run(question)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain_core/_api/deprecation.py", line 191, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain/chains/base.py", line 603, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain_core/_api/deprecation.py", line 191, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain/chains/base.py", line 386, in __call__
    return self.invoke(
           ^^^^^^^^^^^^
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain/chains/base.py", line 167, in invoke
    raise e
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain/chains/base.py", line 157, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain/agents/agent.py", line 1620, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain/agents/agent.py", line 1326, in _take_next_step
    [
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain/agents/agent.py", line 1354, in _iter_next_step
    output = self._action_agent.plan(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain/agents/agent.py", line 461, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain_core/runnables/base.py", line 3424, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain_core/runnables/base.py", line 3410, in transform
    yield from self._transform_stream_with_config(
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain_core/runnables/base.py", line 2205, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain_core/runnables/base.py", line 3372, in _transform
    yield from final_pipeline
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain_core/runnables/base.py", line 1419, in transform
    for ichunk in input:
                  ^^^^^
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain_core/runnables/base.py", line 5632, in transform
    yield from self.bound.transform(
  File "/exacto/abhishek/exactoenv2/lib64/python3.12/site-packages/langchain_core/runnables/base.py", line 1437, in transform
    yield from self.stream(final, config, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exacto/abhishek/responsible_ai/src/llm/phi4_wrapper.py", line 155, in stream
    return loop.run_until_complete(self._to_sync_gen(stream_generator()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 666, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/tasks.py", line 689, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
